name: datahub
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  
dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.49.0
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.1  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.16.0 
  - jupyterhub==5.3.0
  - jupyterlab==4.4.3
  - jupyterlab-git==0.51.1
  - jupyterlab_rise==0.43.1
  - jupytext==1.17.1
  - nbgitpuller==1.2.2
  - notebook==7.4.3
  - otter-grader==6.1.3
  - pip==25.1.1  
  - python==3.11.*
  - sqlite>=3.40
  - libsqlite>=3.40

  # other packages
  #- nodejs=18.*
  - appmode==1.0.0
  - ipykernel = 6.29.5
  - ipywidgets==8.1.5
  - jupyterlab-geojson==3.4.0
  - jupyter-rsession-proxy==2.2.1
  - jupyter-syncthing-proxy==1.0.3
  - nbclassic==1.0.0
  - requests==2.32.3
  - syncthing==1.29.2
  - traitlets=5.14.3

  # vscode
  - jupyter-vscode-proxy==0.6
  - code-server==4.96.2

  # jupyterbook
  - mystmd==1.3.19

  # Base scientific packages that other conda packages we install depend on
  # We don't want to have conda packages depend on pip packages if possible
  - decorator=5.1.1
  - ipympl=0.9.*
  - matplotlib=3.10.*
  - networkx=3.4.2
  - nltk=3.9.1
  - numpy=2.2.*
  - pandas==2.2.3
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - seaborn=0.13.2
  - spacy==3.8.2
  - statsmodels=0.14.4

  # [DH-384], L&S 22, Fall 2024
  # Packages listed below will be used during SP 25
  - typing_extensions==4.12.2
  - spacy-model-en_core_web_sm=3.8.0
  - spacy-model-en_core_web_md=3.8.0

  # ls 88-3; neuro
  - pillow=11.1.0

  # modules
  - beautifulsoup4==4.12.3

  # PS88, Fall '21 and "future iterations of the class."
  # https://github.com/berkeley-dsep-infra/datahub/issues/2925
  - linearmodels==6.1

  # INDENG 142 Spring 2021 (future semesters as well) - https://github.com/berkeley-dsep-infra/datahub/issues/2314
  - fancyimpute==0.7.0

  # 2024-08 workshop, #5908
  - tree==2.2.1
  - ruff==0.8.5

  # Stat 165/265 requires prophet, Spring, 2024
  - prophet==1.1.6

  # ENERES 131, Fall '24 and "Fall semesters for the foreseeable future"
  # [DH-364] https://github.com/berkeley-dsep-infra/datahub/issues/6155
  - openpyxl==3.1.5
  # [DH-393] https://github.com/berkeley-dsep-infra/datahub/issues/6346
  - pyogrio==0.10.0

  # Google spreadsheets, Eric Van Dusen / Keeley Takimoto / Modules
  - gspread-pandas==2.2.3
  - gspread==5.12.4

  # issue #929, SW 282 - fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - pyreadstat==1.2.8

  # issue 954, EPS24 - fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - xarray==2025.1.1

  # issue 1847; LS 22 spring 2021; "likely will need it yearly"
  - python-graphviz==0.20.3

  # [DH-243] https://github.com/berkeley-dsep-infra/datahub/issues/5571, Legal Studies 123, Spring 24; each Spring
  - geopandas==1.1.1
  - rtree==1.3.0

  # sknapp 2023-12-15:  we will eventually move prob140 back to datahub in FA24
  # https://jira-secure.berkeley.edu/browse/DH-203
  - sympy==1.13.3

  # eps 109; fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - ffmpeg-python==0.2.0

  # issue #875, global 150Q/pacs 190 - fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - wordcloud==1.9.4

  # https://github.com/berkeley-dsep-infra/datahub/issues/2950
  # Needed to work with a new enough version of httplib2
  - httplib2==0.22.0

  # Engineering 7 https://github.com/berkeley-dsep-infra/datahub/issues/5337
  - pydantic==2.10.5
  
  # Econ 148, https://github.com/berkeley-dsep-infra/datahub/issues/6791
  - jupysql==0.10.17

  # Econ 148; Spring 2025; https://github.com/berkeley-dsep-infra/datahub/issues/6872
  - lifelines==0.30.0

  # French 80, Fall 2025; https://github.com/berkeley-dsep-infra/datahub/issues/7501
  - geojson==3.2.0
  - pyproj==3.7.2

  - pip:
    - git-credential-helpers==0.2
    - jupyter-shiny-proxy==1.3.0
    - nbconvert[webpdf]==7.16.6

    # Measure popularity of different packages in our hubs
    # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling

    # Econ 148, Spring 2023 https://github.com/berkeley-dsep-infra/datahub/issues/4093
    - pycountry-convert==0.7.2

    # sknapp 2023-12-15:  we will eventually move prob140 back to datahub in FA24
    # https://jira-secure.berkeley.edu/browse/DH-203
    - prob140==0.4.1.6

    # https://github.com/berkeley-dsep-infra/datahub/issues/5497
    - ottr-force-save-labextension==0.1.1

    # [DH-540], Physics 77/88, Fall 2025
    - otter-grader-labextension==0.1.1

    # [DH-319] https://github.com/berkeley-dsep-infra/datahub/issues/5827, ESPM 157
    - ibis-framework[pandas,duckdb]==9.2.0

    # [DH-384], L&S 22, Fall 2024
    # The 0.2.2 conda-forge package is 3y old as of 2025-01 and cannot be
    # installed with newer numpy.
    - lemminflect==0.2.3

    # [DH-557], Data Courses, Fall 2025
    - datascience==0.18.0

    # Adding a11y-checker package to datahub image since it is required for demoing the extension in workshop hub to non Berkeley folks
    - jupyterlab-a11y-checker==0.2.2

    # [DH-488], Legal Studies 123, https://github.com/berkeley-dsep-infra/datahub/issues/6964
    - gensim==4.4.0

    # ATTEMPT TO PUT NEW PACKAGES IN THE CONDA LIST ABOVE FIRST, RATHER THAN PIP



