name: Call Shared Yaml Lint Workflow
on:
  - pull_request  # yamllint disable-line rule:truthy

jobs:
  call-shared-yaml-lint:
    uses: berkeley-dsep-infra/update-deployment/.github/workflows/shared-yaml-lint.yaml@main
